### ISSUE TITLE
Footer overlapping

### ISSUE THREAD

**Issue by hpretl** [michaelroland/jku-templates-presentation-latex#5]
I tend to use extensive date fields (see example), which cause to overlap with the section title. It would be super if this could be avoided in the template by evaluating the size of the date field and taking it into account.

![Screenshot 2023-07-20 at 17 54 01](https://github.com/michaelroland/jku-templates-presentation-latex/assets/57392031/4dd292ef-07fb-431a-86c6-83715fc0a323)

**Comment by michaelroland** [comment]
I would prefer to leave that as-is. Changing that would make it too easy for users to break the style by overfilling the date field. Btw. the \footerdate should automatically wrap lines if you put custom content into the \footerdate field directly (instead of the indirection through the \date command, try:
```latex
\footerdate{%
    \copyright~2017--2023 (v2.3) H.~Pretl%
}
```

If you really want to extend the \footerdate field, you can easily move the content of the \footerdate field around with negative \hspace (around 1.0-2.0 times the width of the footerdate block should work depending on extra logos and slide format):

```latex
\footerdate{%
    \hspace*{-2.0\textwidth}%
    \parbox[b]{2.0\textwidth}{\raggedleft%
        This text extends to the left of the date into the logo area.%
    }\ \insertshortdate%
}
```
or
```latex
\footerdate{%
    \hspace*{-2.0\textwidth}%
    \parbox[b]{2.0\textwidth}{\raggedleft%
        \copyright~2017--2023
    }\ (v2.3) H.~Pretl%
}
```

Alternatively, you could add both footer and copyright info to the \footerdate field:
```latex
\footer{}
\footerdate{%
    \mbox{%
        \copyright~2017--2023 (v2.3) H.~Pretl%
        \quad\insertsectionhead%
    }%
}
```

**Comment by hpretl** [comment]
Thank you, I go with your last proposal, that works exactly as I need it.
